### PR TITLE
Feedback cmd, unregistration possibility and yearly update

### PR DESCRIPTION
**Pull request by OscarVsp**
Add a /feedback cmd available to everyone to send feedback about issue or improvement ideas directly from discord.
#13  Change the /ulb cmd to make unregistration possible when the user using it is registered.

### CODE REVIEW

**Comment by OscarVsp** [comment]
#14  Adding yearly-update feature

**Review by LucasPlacentino — APPROVED** [review]
looks good

**Comment by LucasPlacentino** [comment]
builds not working atm 😢 currently trying out different docker python base images and versions

**Comment by LucasPlacentino** [comment]
LucasPlacentino@3b82ff4  
Switched docker python base image to alpine, need to test on test server

**Comment by LucasPlacentino** [comment]
> [LucasPlacentino/ULBDiscordBot@3b82ff4](https://github.com/LucasPlacentino/ULBDiscordBot/commit/3b82ff4) Switched docker python base image to alpine, need to test on test server

tested, works 👍

**Pull request merged**
